### ISSUE TITLE
citeseq_data.rda contains faulty expr

### ISSUE THREAD

**Issue by FelixTheStudent** [anders-biostat/rlc_tutorial#2]
@simon-anders
recompute the citeseq_data.rda object, this time transposing the `expr` object. Thus, instead of
expr <-  apply( countMatrix, 1, function( x ) sqrt( x / sf ) )  
do 
expr <- t( apply( countMatrix, 1, function( x ) sqrt( x / sf ) ) )

**Comment by simon-anders** [comment]
fixed in commit cf1869b
